### ISSUE TITLE
환경설정

### ISSUE THREAD

**Issue by cheewr85** [FS-Study/React-Practice#4]
# Task

Task Description : 템플릿 설정 및 깃허브 설정 초기 세팅

## To-Do

- [x] github VSCode 연동
- [x] branch 사전 작성
- [x] template 작성
- [x] 기능대로 Issue 발행 및 업무 분담
- [x] 프로젝트 파일 초기 세팅
