### ISSUE TITLE
메인 컴포넌트 구현

### ISSUE THREAD

**Issue by cheewr85** [FS-Study/React-Practice#6]
# Task

**Task Description**
1. 로그인 컴포넌트 구현
2. 안내 문구 컴포넌트 구현
3. 로그인 폼 컴포넌트 구현

## To-Do

- [x] 로그인 메인 컴포넌트(백그라운드 이미지 & 배경 적용)
- [x] 안내 문구 text 추가(CSS 효과 확실히)
- [x] 폼 컴포넌트(form에 대한 state 처리 & 유효처리 => 노션 참조)
- [x] 로그인 컴포넌트에 import 해서 통합
