### ISSUE TITLE
Modal 컴포넌트

### ISSUE THREAD

**Issue by cheewr85** [FS-Study/React-Practice#7]
# Task

**Task Description**
1. Modal 컴포넌트 공통 구현 및 적용
2. login 결과에 대한 Modal 컴포넌트 구현 적용
3. 이용약관에 대해서도 Modal 컴포넌트 적용

## To-Do

- [x] Modal 컴포넌트 공통 사항 구현
- [x] 로그인 결과에 대한 Modal 컴포넌트 적용
- [x] 이용약관 내용 Modal 컴포넌트 적용
