### ISSUE TITLE
Context 처리

### ISSUE THREAD

**Issue by cheewr85** [FS-Study/React-Practice#8]
# Task

Task Description : form 양식에서 오는 데이터에 대해서 context로 저장 및 처리, state 관리

## To-Do

- [x] Context 활용해서 필요한 state 값 통합 관리 처리
- [x] state 값에 따른 구분 처리(Modal 컴포넌트)
- [x] useReducer 함수 처리 & form 활용
